# Generated by Django 4.2.1 on 2023-06-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='group_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='type',
            field=models.CharField(blank=True, choices=[('Unofficial', 'Amatoriale'), ('Official', 'Ufficiale')], max_length=32, null=True),
        ),
    ]
