# Generated by Django 4.2.1 on 2023-06-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_matches_club_alter_matches_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
