# Generated by Django 4.2.1 on 2023-06-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_matches_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='number_subscibed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='group_size',
            field=models.IntegerField(blank=True, default=4),
        ),
    ]
