# Generated by Django 4.2.1 on 2023-06-18 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_irons_ironownership'),
        ('matches', '0006_rename_number_subscibed_matches_number_subscribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.matches')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.playerprofile')),
            ],
        ),
    ]
