# Generated by Django 4.2.1 on 2023-06-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_matchbooking'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='matchbooking',
            constraint=models.UniqueConstraint(fields=('profile', 'match'), name='Max 1 booking per macth'),
        ),
    ]
