# Generated by Django 4.2.1 on 2023-05-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_playerprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
