# Generated by Django 4.2.1 on 2023-05-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_playerprofile_address_alter_playerprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='experience',
            field=models.CharField(choices=[('< 1', '< 1'), ('1 - 3', '1 - 3'), ('> 3', ' > 3')], default='-1', max_length=20),
        ),
    ]
