# Generated by Django 4.2.1 on 2023-05-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_playerprofile_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
