# Generated by Django 4.2.1 on 2023-05-24 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_playerprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='address',
        ),
        migrations.CreateModel(
            name='clubProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_holes', models.IntegerField(choices=[(9, 9), (18, 18)], default=9)),
                ('name', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('img', models.ImageField(default='default_club.jpeg', upload_to='image_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
