# Generated by Django 4.2.1 on 2023-05-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_playerprofile_address_clubprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubprofile',
            name='city',
            field=models.CharField(blank=True, default='Other', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='clubprofile',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
