# Generated by Django 4.2.1 on 2023-05-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_clubprofile_city_alter_clubprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
