# Generated by Django 4.2.1 on 2023-05-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_playerprofile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='experience',
            field=models.CharField(choices=[('Meno di un anno', '< 1'), ('Tra uno e tre anni', '1 - 3'), ('Più di 3 anni', ' > 3')], default='-1', max_length=20),
        ),
    ]
