# Generated by Django 4.2.1 on 2023-05-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_playerprofile_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='experience',
            field=models.CharField(choices=[('< 1', 'Meno di un anno'), ('1 - 3', 'Tra uno e tre anni'), (' > 3', 'Più di 3 anni')], default='-1', max_length=20),
        ),
    ]
