# Generated by Django 4.2.1 on 2023-06-03 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_options_customuser_unique_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Irons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('shot_type', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='IronOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_having', models.DateField(blank=True, null=True)),
                ('iron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.irons')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.playerprofile')),
            ],
        ),
    ]
