
name: Build and push to container registry


on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: Checkout repository
          uses: actions/checkout@v2
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: https://testgolf.azurecr.io/
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/golfapp:${{ github.sha }} -f Dockerfile .
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/golfapp:${{ github.sha }}
